
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  7 2026 16:13:55 IST (Sep  7 2026 10:43:55 UTC)

// Verification Directory fv/sram_4x4 

module sram_4x4(clk, we, addr, din, dout);
  input clk, we;
  input [1:0] addr;
  input [3:0] din;
  output [3:0] dout;
  wire clk, we;
  wire [1:0] addr;
  wire [3:0] din;
  wire [3:0] dout;
  wire [3:0] row_we;
  wire [15:0] cell_q;
  wire n_0, n_1, n_2, n_4, n_5, n_8, n_9, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_39, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49;
  sram_cell cell_00(.clk (clk), .we (row_we[0]), .din (din[0]), .dout
       (cell_q[0]));
  sram_cell cell_01(.clk (clk), .we (row_we[0]), .din (din[1]), .dout
       (cell_q[1]));
  sram_cell cell_02(.clk (clk), .we (row_we[0]), .din (din[2]), .dout
       (cell_q[2]));
  sram_cell cell_03(.clk (clk), .we (row_we[0]), .din (din[3]), .dout
       (cell_q[3]));
  sram_cell cell_10(.clk (clk), .we (row_we[1]), .din (din[0]), .dout
       (cell_q[4]));
  sram_cell cell_11(.clk (clk), .we (row_we[1]), .din (din[1]), .dout
       (cell_q[5]));
  sram_cell cell_12(.clk (clk), .we (row_we[1]), .din (din[2]), .dout
       (cell_q[6]));
  sram_cell cell_13(.clk (clk), .we (row_we[1]), .din (din[3]), .dout
       (cell_q[7]));
  sram_cell cell_20(.clk (clk), .we (row_we[2]), .din (din[0]), .dout
       (cell_q[8]));
  sram_cell cell_21(.clk (clk), .we (row_we[2]), .din (din[1]), .dout
       (cell_q[9]));
  sram_cell cell_22(.clk (clk), .we (row_we[2]), .din (din[2]), .dout
       (cell_q[10]));
  sram_cell cell_23(.clk (clk), .we (row_we[2]), .din (din[3]), .dout
       (cell_q[11]));
  sram_cell cell_30(.clk (clk), .we (row_we[3]), .din (din[0]), .dout
       (cell_q[12]));
  sram_cell cell_31(.clk (clk), .we (row_we[3]), .din (din[1]), .dout
       (cell_q[13]));
  sram_cell cell_32(.clk (clk), .we (row_we[3]), .din (din[2]), .dout
       (cell_q[14]));
  sram_cell cell_33(.clk (clk), .we (row_we[3]), .din (din[3]), .dout
       (cell_q[15]));
  NAND2X8 g360__2398(.A (n_20), .B (n_19), .Y (dout[3]));
  OR2X6 g361__5107(.A (n_22), .B (n_18), .Y (dout[2]));
  NAND2X8 g362__6260(.A (n_17), .B (n_16), .Y (dout[0]));
  NAND2X8 g363__4319(.A (n_21), .B (n_15), .Y (dout[1]));
  OAI22X4 g364__8428(.A0 (n_0), .A1 (n_45), .B0 (n_1), .B1 (n_9), .Y
       (n_22));
  AOI22X4 g365__5526(.A0 (cell_q[1]), .A1 (n_46), .B0 (cell_q[5]), .B1
       (n_8), .Y (n_21));
  AOI21X4 g366__6783(.A0 (cell_q[7]), .A1 (n_8), .B0 (n_13), .Y (n_20));
  AOI22X4 g367__3680(.A0 (cell_q[3]), .A1 (n_43), .B0 (cell_q[11]), .B1
       (n_5), .Y (n_19));
  OAI21X2 g368__1617(.A0 (n_4), .A1 (n_48), .B0 (n_12), .Y (n_18));
  AOI22X4 g369__2802(.A0 (cell_q[0]), .A1 (n_47), .B0 (cell_q[8]), .B1
       (n_5), .Y (n_17));
  AOI21X4 g370__1705(.A0 (cell_q[4]), .A1 (n_8), .B0 (n_14), .Y (n_16));
  AOI21X4 g371__5122(.A0 (cell_q[9]), .A1 (n_5), .B0 (n_11), .Y (n_15));
  NOR2BX1 g372__8246(.AN (cell_q[12]), .B (n_49), .Y (n_14));
  NOR2BXL g373__7098(.AN (we), .B (n_9), .Y (row_we[1]));
  AND2XL g374__6131(.A (we), .B (n_43), .Y (row_we[0]));
  NOR2BX2 g375__1881(.AN (cell_q[15]), .B (n_48), .Y (n_13));
  NOR2BXL g376__5115(.AN (we), .B (n_44), .Y (row_we[2]));
  NOR2BXL g377__7482(.AN (we), .B (n_48), .Y (row_we[3]));
  NAND2X4 g378__4733(.A (cell_q[2]), .B (n_46), .Y (n_12));
  NOR2BX1 g379__6161(.AN (cell_q[13]), .B (n_49), .Y (n_11));
  CLKINVX8 g380(.A (n_9), .Y (n_8));
  NAND2X8 g382__9315(.A (addr[0]), .B (n_2), .Y (n_9));
  CLKINVX8 g383(.A (n_44), .Y (n_5));
  INVX1 g386(.A (cell_q[14]), .Y (n_4));
  CLKINVX20 g388(.A (addr[1]), .Y (n_2));
  INVX1 g389(.A (cell_q[6]), .Y (n_1));
  INVX1 g390(.A (cell_q[10]), .Y (n_0));
  CLKINVX20 fopt(.A (addr[0]), .Y (n_39));
  NOR2X2 g381_0__9945(.A (addr[0]), .B (addr[1]), .Y (n_43));
  NAND2X8 g392__2883(.A (addr[1]), .B (n_39), .Y (n_44));
  NAND2X6 g385_0__2346(.A (addr[1]), .B (n_39), .Y (n_45));
  NOR2X8 g393__1666(.A (addr[0]), .B (addr[1]), .Y (n_46));
  NOR2X2 g391_0__7410(.A (addr[0]), .B (addr[1]), .Y (n_47));
  NAND2X6 g394__6417(.A (addr[0]), .B (addr[1]), .Y (n_48));
  NAND2X8 g384_0__5477(.A (addr[0]), .B (addr[1]), .Y (n_49));
endmodule

